#!/bin/bash
prompt="$1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26} ${27} ${28} ${29} ${30} ${31} ${32} ${33} ${34} ${35} ${36} ${37} ${38} ${39} ${40} ${41} ${42} ${43} ${44} ${45} ${46}"
curlOutput=$(curl -s -X POST -H "Content-Type: application/json" "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" -d "{\"contents\":[{\"parts\":[{\"text\":\"$prompt\"}]}]}" | jq '.candidates.[0].content.parts.[0].text')


echo -e "\n\n"
#temp_file=$(mktemp)
echo "from rich.console import Console; from rich.markdown import Markdown; cl=Console(record = True); md=Markdown($curlOutput); cl.print(md); " | python | tee >(wl-copy)
#echo $curlOutput
echo -e "\n\n"
