#!/bin/bash
#


IN=$(gsettings get org.gnome.desktop.background picture-uri)
subsi1=${IN:8:200}
xmlFile=${subsi1%\'*}
extension="${xmlFile##*.}"
if [[ $extension == "xml" ]]; then
	# file is an xml
	imageFile=$(xml sel -t -v 'background/static/file' $xmlFile | head -n1)
else
	imageFile=$xmlFile
fi

echo $imageFile
