#!/bin/bash

requestString="
  \"contents\":[
    {
      \"parts\":[
        {\"text\": \"Explain this mathematical equation and convert this into latex format and also include the relevant derivation and solution of it\"},
        {
          \"inline_data\": {
            \"mime_type\":\"image/jpeg\",
            \"data\": \"'$(base64 -w0 $1)'\"
          }
        }
      ]
    }
]
"

echo -e "request string is: $requestString"

curlOutput=$(curl -v https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-vision:generateContent?key=${MATHNOTE_KEY} \
        -H 'Content-Type: application/json' \
        -d '$requestString' | jq '.candidates.[0].content.parts.[0].text' \
)

echo "curl out => $curlOutput"

echo -e "\n\n"
echo "from rich.console import Console; from rich.markdown import Markdown; cl=Console(); md=Markdown($curlOutput); cl.print(md);" | python
echo -e "\n\n"

