#!/bin/bash

# Function to generate a random password
generate_password() {
    local length=$1
    # Define the character set
    local charset='A-Za-z0-9!@#$%^&*()_+'
    
    # Generate the password using /dev/urandom and tr to filter characters
    < /dev/urandom tr -dc "$charset" | head -c "$length"
    echo
}


if [ $# -eq 0 ]; then
  password_length=12
else
  password_length=$1
fi

# Generate and print the password
generate_password "$password_length"
