#!/bin/bash
#
# Symbolics, Fluent, We Yamle, Zorin Mountain fog, Desert, Sunset, Monterey, SolidMountain, LofiCity, ZorinBlur,
#
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/ZorinBlur.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Drool.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Disco.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Symbolics.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/EOS-WeYamle.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/ChromeOSGreens.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/ChromeOSWind.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Fluent.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Firewatch2.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/ZorinMountainFog.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Desert.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/EOS-Sunset.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Monterey.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/SolidMountain.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/LofiCity.xml
#settimed /usr/share/backgrounds/Dynamic_Wallpapers/Blobs.xml
settimed /usr/share/backgrounds/Dynamic_Wallpapers/$(ls /usr/share/backgrounds/Dynamic_Wallpapers | grep xml | shuf -n1)
