#!/bin/bash
#from random import random
#print(["Heads", "Tails"][int(random()*2)])
clear
#echo "h or t ? " | cowsay -f morpheus
echo "h or t ? " | cowsay

res=$(python3 -c 'from random import random ; print(["h", "t"][int(random()*2)])')

read inp

echo $inp
echo $res


if  [[ ! ( $inp == 'h' || $inp == 't' ) ]]; then
    clear
    #echo 'Hansu?' | cowsay -f joker
    echo 'Hansu?' | cowsay
elif [[ $inp == $res ]]; then
    clear
    #echo "You're goddamn right" | cowsay -f walter
    echo "You're goddamn right" | cowsay
else
    clear
    echo "bhains chara jaake" | cowsay
fi
