#!/usr/bin/bash

mongosh $MONGODB_XOLLEGE --eval 'db.colleges.aggregate([ { $group: { _id: "$details.location.state", count: { $sum: 1 } } }, { $project: { _id: 0, state: "$_id", count: 1 } }] ).forEach((doc) => { db.collegeStateCount.updateOne( { state: doc.state }, { $set: { count: doc.count } }, { upsert: true } ); })'
